Phase 3: retarget CI from jdk21u to jdk25u
Introduce jdk_version/jdku_version m4 macros so that the next upgrade is a
one-line change, and move the build containers to cf-ubuntu-jdk25-plus (the
merged tree is JDK 26-ea, which needs a JDK 25 boot JDK).

canary_version, latest_version, and the cftests_*_jdk17/21 jobs are left alone:
they name the JDKs that run the Checker Framework, not the JDK being annotated.

diff --git a/.azure/azure-pipelines.yml b/.azure/azure-pipelines.yml
--- a/.azure/azure-pipelines.yml
+++ b/.azure/azure-pipelines.yml
@@ -8,7 +8,7 @@ jobs:
   - job: build_jdk
     pool:
       vmImage: 'ubuntu-latest'
-    container: mdernst/cf-ubuntu-jdk21-plus:latest
+    container: mdernst/cf-ubuntu-jdk25-plus:latest
     steps:
       - bash: |
           whoami
@@ -29,10 +29,10 @@ jobs:
         # - bash: make -C /jdk run-test-tier1
         #   displayName: make run-test-tier1
 
-  - job: build_jdk21u
+  - job: build_jdk25u
     pool:
       vmImage: 'ubuntu-latest'
-    container: mdernst/cf-ubuntu-jdk21-plus:latest
+    container: mdernst/cf-ubuntu-jdk25-plus:latest
     timeoutInMinutes: 0
     steps:
       - bash: |
@@ -56,29 +56,29 @@ jobs:
             else mkdir -p /tmp/$USER && git -C /tmp/$USER clone --depth=1 -q https://github.com/plume-lib/plume-scripts.git ; \
           fi
         displayName: plume-scripts
-        # This creates ../jdk21u .
+        # This creates ../jdk[]jdku_version .
         # Run `git-clone-related` without a limit on depth, because if the depth is
         # too small, the merge will fail.  Don't use "--filter=blob:none" because that
         # leads to "fatal: remote error:  filter 'combine' not supported".
       - bash: |
           set -ex
           echo "pwd = $(pwd)"
-          if test -d ../jdk21u; then
-            echo "../jdk21u should not exist yet"
+          if test -d ../jdk25u; then
+            echo "../jdk25u should not exist yet"
             false
           fi
           df .
-          /tmp/$USER/git-scripts/git-clone-related typetools jdk21u ../jdk21u --single-branch
+          /tmp/$USER/git-scripts/git-clone-related typetools jdk25u ../jdk25u --single-branch
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
           git config --global core.longpaths true
           git config --global core.protectNTFS false
-          cd ../jdk21u
+          cd ../jdk25u
           git diff --exit-code
-        displayName: clone-related-jdk21u
+        displayName: clone-related-jdk25u
       - bash: |
-          git config --global --add safe.directory $(cd ../jdk21u && pwd)
-          cd ../jdk21u && git status
+          git config --global --add safe.directory $(cd ../jdk25u && pwd)
+          cd ../jdk25u && git status
           /tmp/$USER/plume-scripts/ci-org-and-branch typetools --debug
           eval $(/tmp/$USER/plume-scripts/ci-org-and-branch typetools)
           echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
@@ -92,31 +92,31 @@ jobs:
           git config --global core.longpaths true
           git config --global core.protectNTFS false
           git config --global merge.conflictstyle diff3
-          cd ../jdk21u && git status
+          cd ../jdk25u && git status
           eval $(/tmp/$USER/plume-scripts/ci-org-and-branch typetools)
           echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
-          cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (git --version && git show | head -100 && git status && git diff | head -1000 && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md " && false)
+          cd ../jdk25u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (git --version && git show | head -100 && git status && git diff | head -1000 && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md " && false)
         displayName: git merge
-      - bash: cd ../jdk21u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
+      - bash: cd ../jdk25u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
         displayName: configure
-      - bash: cd ../jdk21u && make jdk
+      - bash: cd ../jdk25u && make jdk
         displayName: make jdk
         ## This works only after `make images`
-        # - bash: cd ../jdk21u && build/*/images/jdk/bin/java -version
+        # - bash: cd ../jdk[]jdku_version && build/*/images/jdk/bin/java -version
         #   displayName: version
-        # - bash: make -C /jdk21u run-test-tier1
+        # - bash: make -C /jdk[]jdku_version run-test-tier1
         #   timeoutInMinutes: 0
         #   displayName: make run-test-tier1
-        # - bash: make -C /jdk21u :test/jdk:tier1
+        # - bash: make -C /jdk[]jdku_version :test/jdk:tier1
         ## Temporarily comment out because of trouble finding junit and jasm
-        # - bash: cd ../jdk21u && make run-test TEST="jtreg:test/jdk:tier1"
+        # - bash: cd ../jdk[]jdku_version && make run-test TEST="jtreg:test/jdk:tier1"
         #   timeoutInMinutes: 0
         #   displayName: make run-test
 
   - job: canary_jobs
     dependsOn:
       - build_jdk
-      - build_jdk21u
+      - build_jdk25u
     pool:
       vmImage: 'ubuntu-latest'
     steps:
